/*
  Sketch generated by the Arduino IoT Cloud Thing "Thing1"
  https://create.arduino.cc/cloud/things/3c6c4cf7-31f4-4d93-9278-dede6385b636

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int test_bat;
  int test_temp1;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"


int LED = 2;


void setup() {
  pinMode(LED, OUTPUT);

  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  test_bat++;
  if (test_bat > 60)
  {
    test_bat = 30;
  }
  test_temp1++;
  if (test_temp1 > 60)
  {
    test_temp1 = 40;
    test_msg = "Überspannung 2";
  }
  else
  {
    test_msg = "";
  }
  delay(500);
}

/*
  Since TestBat is READ_WRITE variable, onTestBatChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTestBatChange()  {
  // Add your code here to act upon TestBat change
}
/*
  Since TestTemp1 is READ_WRITE variable, onTestTemp1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onTestTemp1Change()  {
  // Add your code here to act upon TestTemp1 change
}

void onTestLedswitchChange() {
  // Do something
  if(test_ledswitch){
    digitalWrite(LED, HIGH);
  }
  else{
    digitalWrite(LED, LOW);
  }
}
