// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

#define SECRET_SSID "HTC U11"
#define SECRET_PASS "e40aba40ba94"
#define SECRET_DEVICE_KEY "EOGNKTDXDCYHLKJHB4IT"

const char THING_ID[]           = "3c6c4cf7-31f4-4d93-9278-dede6385b636";
const char DEVICE_LOGIN_NAME[]  = "b07531af-fa14-4992-885b-99670b7e8bf4";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY;    // Secret device password

void onTestBatChange();
void onTestTemp1Change();
void onTestLedswitchChange();

String test_msg;
int test_bat;
int test_temp1;
bool test_ledswitch;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(test_msg, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(test_bat, READWRITE, ON_CHANGE, onTestBatChange);
  ArduinoCloud.addProperty(test_temp1, READWRITE, ON_CHANGE, onTestTemp1Change);
  ArduinoCloud.addProperty(test_ledswitch, READWRITE, ON_CHANGE, onTestLedswitchChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
